# Dependencies
markdown:         kramdown
highlighter:      rouge

domain: dks2000dks.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://dks2000dks.github.io  # the base hostname and protocol for your site, e.g. http://example.com
# baseurl: /REPOSITORY-NAME/         # place folder name if the site is served in a subfolder

# Setup
title:            Krishna Srikar Durbha
url:              linkedin.com/in/krishna-srikar-durbha/
# the optional subpath of your site, e.g. "/blog"
# NB: This applies to all pages in your Jekyll site.
# If you want to move just the blog index pages but keep
# other pages at root, see the paginate_path and
# sidebar_blog_link below.

author:
  name:           Krishna Srikar Durbha # Original Author: 'Andrew Fong'
  url:            linkedin.com/in/krishna-srikar-durbha/

paginate:         5
# paginate_path:    '/page:num'
# Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'
# By default, your home page is your blog page. If you change your paginate_path, set this to the root of the paginate_path to enable a separate blog link.
